import { ToolDefinition } from '../types';

/**
 * Complete registry of all 192 tools across 8 categories
 * This file contains the complete tool definitions
 */

export const ALL_TOOLS: ToolDefinition[] = [
  // ==================== PDF TOOLS (35) ====================
  { id: 'pdf-merge', name: 'PDF Merge', category: 'pdf', description: 'Merge multiple PDF files into one', acceptedFormats: ['.pdf'], multipleFiles: true, settings: [] },
  { id: 'pdf-split', name: 'PDF Split', category: 'pdf', description: 'Split PDF into multiple files', acceptedFormats: ['.pdf'], multipleFiles: false, settings: [{ key: 'mode', type: 'select', label: 'Split Mode', default: 'pages', options: [{ value: 'pages', label: 'Every N pages' }, { value: 'range', label: 'Page ranges' }] }] },
  { id: 'pdf-compress', name: 'PDF Compress', category: 'pdf', description: 'Compress PDF file size', acceptedFormats: ['.pdf'], multipleFiles: false, settings: [{ key: 'quality', type: 'select', label: 'Quality', default: 'medium', options: [{ value: 'screen', label: 'Screen (72 dpi)' }, { value: 'ebook', label: 'eBook (150 dpi)' }] }] },
  { id: 'pdf-to-images', name: 'PDF to Images', category: 'pdf', description: 'Convert PDF pages to images', acceptedFormats: ['.pdf'], multipleFiles: false, settings: [] },
  { id: 'pdf-to-word', name: 'PDF to Word', category: 'pdf', description: 'Convert PDF to DOCX', acceptedFormats: ['.pdf'], multipleFiles: false, settings: [] },
  { id: 'pdf-to-excel', name: 'PDF to Excel', category: 'pdf', description: 'Convert PDF tables to Excel', acceptedFormats: ['.pdf'], multipleFiles: false, settings: [] },
  { id: 'pdf-to-ppt', name: 'PDF to PowerPoint', category: 'pdf', description: 'Convert PDF to PPTX', acceptedFormats: ['.pdf'], multipleFiles: false, settings: [] },
  { id: 'pdf-watermark', name: 'PDF Watermark', category: 'pdf', description: 'Add watermark to PDF', acceptedFormats: ['.pdf'], multipleFiles: false, settings: [{ key: 'text', type: 'string', label: 'Watermark Text', required: true }] },
  { id: 'pdf-rotate', name: 'PDF Rotate', category: 'pdf', description: 'Rotate PDF pages', acceptedFormats: ['.pdf'], multipleFiles: false, settings: [{ key: 'angle', type: 'select', label: 'Rotation', default: '90', options: [{ value: '90', label: '90°' }, { value: '180', label: '180°' }] }] },
  { id: 'pdf-page-numbers', name: 'PDF Page Numbers', category: 'pdf', description: 'Add page numbers', acceptedFormats: ['.pdf'], multipleFiles: false, settings: [] },
  { id: 'pdf-extract-text', name: 'PDF Extract Text', category: 'pdf', description: 'Extract text from PDF', acceptedFormats: ['.pdf'], multipleFiles: false, settings: [] },
  { id: 'pdf-extract-images', name: 'PDF Extract Images', category: 'pdf', description: 'Extract images', acceptedFormats: ['.pdf'], multipleFiles: false, settings: [] },
  { id: 'pdf-remove-pages', name: 'PDF Remove Pages', category: 'pdf', description: 'Remove specific pages', acceptedFormats: ['.pdf'], multipleFiles: false, settings: [] },
  { id: 'pdf-reorder', name: 'PDF Reorder', category: 'pdf', description: 'Reorder pages', acceptedFormats: ['.pdf'], multipleFiles: false, settings: [] },
  { id: 'pdf-password-protect', name: 'PDF Password Protect', category: 'pdf', description: 'Add password protection', acceptedFormats: ['.pdf'], multipleFiles: false, settings: [{ key: 'password', type: 'string', label: 'Password', required: true }] },
  { id: 'pdf-remove-password', name: 'PDF Remove Password', category: 'pdf', description: 'Remove password', acceptedFormats: ['.pdf'], multipleFiles: false, settings: [{ key: 'password', type: 'string', label: 'Password', required: true }] },
  { id: 'pdf-metadata', name: 'PDF Metadata', category: 'pdf', description: 'Edit metadata', acceptedFormats: ['.pdf'], multipleFiles: false, settings: [] },
  { id: 'pdf-ocr', name: 'PDF OCR', category: 'pdf', description: 'Add OCR text layer', acceptedFormats: ['.pdf'], multipleFiles: false, settings: [] },
  { id: 'pdf-sign', name: 'PDF Sign', category: 'pdf', description: 'Add signature', acceptedFormats: ['.pdf'], multipleFiles: false, settings: [] },
  { id: 'pdf-redact', name: 'PDF Redact', category: 'pdf', description: 'Redact information', acceptedFormats: ['.pdf'], multipleFiles: false, settings: [] },
  { id: 'pdf-flatten', name: 'PDF Flatten', category: 'pdf', description: 'Flatten forms', acceptedFormats: ['.pdf'], multipleFiles: false, settings: [] },
  { id: 'pdf-linearize', name: 'PDF Linearize', category: 'pdf', description: 'Optimize for web', acceptedFormats: ['.pdf'], multipleFiles: false, settings: [] },
  { id: 'pdf-repair', name: 'PDF Repair', category: 'pdf', description: 'Repair corrupted PDF', acceptedFormats: ['.pdf'], multipleFiles: false, settings: [] },
  { id: 'pdf-compare', name: 'PDF Compare', category: 'pdf', description: 'Compare two PDFs', acceptedFormats: ['.pdf'], multipleFiles: true, settings: [] },
  { id: 'pdf-header-footer', name: 'PDF Header/Footer', category: 'pdf', description: 'Add headers/footers', acceptedFormats: ['.pdf'], multipleFiles: false, settings: [] },
  { id: 'pdf-background', name: 'PDF Background', category: 'pdf', description: 'Add background', acceptedFormats: ['.pdf'], multipleFiles: false, settings: [] },
  { id: 'pdf-bookmarks', name: 'PDF Bookmarks', category: 'pdf', description: 'Add bookmarks', acceptedFormats: ['.pdf'], multipleFiles: false, settings: [] },
  { id: 'pdf-crop', name: 'PDF Crop', category: 'pdf', description: 'Crop pages', acceptedFormats: ['.pdf'], multipleFiles: false, settings: [] },
  { id: 'pdf-grayscale', name: 'PDF Grayscale', category: 'pdf', description: 'Convert to grayscale', acceptedFormats: ['.pdf'], multipleFiles: false, settings: [] },
  { id: 'pdf-optimize-web', name: 'PDF Optimize Web', category: 'pdf', description: 'Optimize for web', acceptedFormats: ['.pdf'], multipleFiles: false, settings: [] },
  { id: 'pdf-form-fill', name: 'PDF Form Fill', category: 'pdf', description: 'Fill PDF forms', acceptedFormats: ['.pdf'], multipleFiles: false, settings: [] },
  { id: 'pdf-convert-pdfa', name: 'PDF to PDF/A', category: 'pdf', description: 'Convert to PDF/A', acceptedFormats: ['.pdf'], multipleFiles: false, settings: [] },
  { id: 'pdf-portfolio', name: 'PDF Portfolio', category: 'pdf', description: 'Create portfolio', acceptedFormats: ['.pdf'], multipleFiles: true, settings: [] },
  { id: 'pdf-reduce-size', name: 'PDF Reduce Size', category: 'pdf', description: 'Reduce file size', acceptedFormats: ['.pdf'], multipleFiles: false, settings: [] },
  { id: 'pdf-print-ready', name: 'PDF Print Ready', category: 'pdf', description: 'Prepare for printing', acceptedFormats: ['.pdf'], multipleFiles: false, settings: [] },

  // ==================== WORD TOOLS (25) ====================
  { id: 'word-to-pdf', name: 'Word to PDF', category: 'word', description: 'Convert to PDF', acceptedFormats: ['.docx', '.doc'], multipleFiles: false, settings: [] },
  { id: 'word-to-html', name: 'Word to HTML', category: 'word', description: 'Convert to HTML', acceptedFormats: ['.docx', '.doc'], multipleFiles: false, settings: [] },
  { id: 'word-to-markdown', name: 'Word to Markdown', category: 'word', description: 'Convert to Markdown', acceptedFormats: ['.docx', '.doc'], multipleFiles: false, settings: [] },
  { id: 'word-to-txt', name: 'Word to Text', category: 'word', description: 'Extract text', acceptedFormats: ['.docx', '.doc'], multipleFiles: false, settings: [] },
  { id: 'word-to-images', name: 'Word to Images', category: 'word', description: 'Convert to images', acceptedFormats: ['.docx', '.doc'], multipleFiles: false, settings: [] },
  { id: 'word-merge', name: 'Word Merge', category: 'word', description: 'Merge documents', acceptedFormats: ['.docx', '.doc'], multipleFiles: true, settings: [] },
  { id: 'word-split', name: 'Word Split', category: 'word', description: 'Split document', acceptedFormats: ['.docx', '.doc'], multipleFiles: false, settings: [] },
  { id: 'word-compress', name: 'Word Compress', category: 'word', description: 'Compress file', acceptedFormats: ['.docx', '.doc'], multipleFiles: false, settings: [] },
  { id: 'word-watermark', name: 'Word Watermark', category: 'word', description: 'Add watermark', acceptedFormats: ['.docx', '.doc'], multipleFiles: false, settings: [] },
  { id: 'word-metadata', name: 'Word Metadata', category: 'word', description: 'Edit metadata', acceptedFormats: ['.docx', '.doc'], multipleFiles: false, settings: [] },
  { id: 'word-password', name: 'Word Password', category: 'word', description: 'Add password', acceptedFormats: ['.docx', '.doc'], multipleFiles: false, settings: [] },
  { id: 'word-remove-password', name: 'Word Remove Password', category: 'word', description: 'Remove password', acceptedFormats: ['.docx', '.doc'], multipleFiles: false, settings: [] },
  { id: 'word-find-replace', name: 'Word Find & Replace', category: 'word', description: 'Find and replace', acceptedFormats: ['.docx', '.doc'], multipleFiles: false, settings: [] },
  { id: 'word-compare', name: 'Word Compare', category: 'word', description: 'Compare documents', acceptedFormats: ['.docx', '.doc'], multipleFiles: true, settings: [] },
  { id: 'word-page-count', name: 'Word Page Count', category: 'word', description: 'Count pages/words', acceptedFormats: ['.docx', '.doc'], multipleFiles: false, settings: [] },
  { id: 'word-remove-comments', name: 'Word Remove Comments', category: 'word', description: 'Remove comments', acceptedFormats: ['.docx', '.doc'], multipleFiles: false, settings: [] },
  { id: 'word-extract-images', name: 'Word Extract Images', category: 'word', description: 'Extract images', acceptedFormats: ['.docx', '.doc'], multipleFiles: false, settings: [] },
  { id: 'word-format-clean', name: 'Word Format Clean', category: 'word', description: 'Clean formatting', acceptedFormats: ['.docx', '.doc'], multipleFiles: false, settings: [] },
  { id: 'word-sign', name: 'Word Sign', category: 'word', description: 'Add signature', acceptedFormats: ['.docx', '.doc'], multipleFiles: false, settings: [] },
  { id: 'word-toc', name: 'Word TOC', category: 'word', description: 'Generate TOC', acceptedFormats: ['.docx', '.doc'], multipleFiles: false, settings: [] },
  { id: 'word-mail-merge', name: 'Word Mail Merge', category: 'word', description: 'Mail merge', acceptedFormats: ['.docx', '.doc'], multipleFiles: false, settings: [] },
  { id: 'word-template', name: 'Word Template', category: 'word', description: 'Use templates', acceptedFormats: ['.docx', '.doc'], multipleFiles: false, settings: [] },
  { id: 'word-accessibility', name: 'Word Accessibility', category: 'word', description: 'Check accessibility', acceptedFormats: ['.docx', '.doc'], multipleFiles: false, settings: [] },
  { id: 'word-translate', name: 'Word Translate', category: 'word', description: 'Translate document', acceptedFormats: ['.docx', '.doc'], multipleFiles: false, settings: [] },
  { id: 'pdf-to-word', name: 'PDF to Word', category: 'word', description: 'Convert PDF to Word', acceptedFormats: ['.pdf'], multipleFiles: false, settings: [] },

  // ==================== EXCEL/CSV TOOLS (30) ====================
  { id: 'excel-to-csv', name: 'Excel to CSV', category: 'excel', description: 'Convert to CSV', acceptedFormats: ['.xlsx', '.xls'], multipleFiles: false, settings: [] },
  { id: 'csv-to-excel', name: 'CSV to Excel', category: 'excel', description: 'Convert to Excel', acceptedFormats: ['.csv'], multipleFiles: false, settings: [] },
  { id: 'excel-to-json', name: 'Excel to JSON', category: 'excel', description: 'Convert to JSON', acceptedFormats: ['.xlsx', '.xls'], multipleFiles: false, settings: [] },
  { id: 'excel-to-xml', name: 'Excel to XML', category: 'excel', description: 'Convert to XML', acceptedFormats: ['.xlsx', '.xls'], multipleFiles: false, settings: [] },
  { id: 'excel-to-pdf', name: 'Excel to PDF', category: 'excel', description: 'Convert to PDF', acceptedFormats: ['.xlsx', '.xls'], multipleFiles: false, settings: [] },
  { id: 'excel-merge', name: 'Excel Merge', category: 'excel', description: 'Merge files', acceptedFormats: ['.xlsx', '.xls'], multipleFiles: true, settings: [] },
  { id: 'excel-split', name: 'Excel Split', category: 'excel', description: 'Split file', acceptedFormats: ['.xlsx', '.xls'], multipleFiles: false, settings: [] },
  { id: 'excel-compress', name: 'Excel Compress', category: 'excel', description: 'Compress file', acceptedFormats: ['.xlsx', '.xls'], multipleFiles: false, settings: [] },
  { id: 'csv-clean', name: 'CSV Clean', category: 'excel', description: 'Clean data', acceptedFormats: ['.csv'], multipleFiles: false, settings: [] },
  { id: 'excel-remove-duplicates', name: 'Excel Remove Duplicates', category: 'excel', description: 'Remove duplicates', acceptedFormats: ['.xlsx', '.xls'], multipleFiles: false, settings: [] },
  { id: 'excel-sort-data', name: 'Excel Sort', category: 'excel', description: 'Sort data', acceptedFormats: ['.xlsx', '.xls'], multipleFiles: false, settings: [] },
  { id: 'excel-filter-data', name: 'Excel Filter', category: 'excel', description: 'Filter data', acceptedFormats: ['.xlsx', '.xls'], multipleFiles: false, settings: [] },
  { id: 'excel-transpose', name: 'Excel Transpose', category: 'excel', description: 'Transpose data', acceptedFormats: ['.xlsx', '.xls'], multipleFiles: false, settings: [] },
  { id: 'excel-concatenate', name: 'Excel Concatenate', category: 'excel', description: 'Concatenate columns', acceptedFormats: ['.xlsx', '.xls'], multipleFiles: false, settings: [] },
  { id: 'excel-split-columns', name: 'Excel Split Columns', category: 'excel', description: 'Split columns', acceptedFormats: ['.xlsx', '.xls'], multipleFiles: false, settings: [] },
  { id: 'excel-statistics', name: 'Excel Statistics', category: 'excel', description: 'Calculate stats', acceptedFormats: ['.xlsx', '.xls'], multipleFiles: false, settings: [] },
  { id: 'excel-find-replace', name: 'Excel Find & Replace', category: 'excel', description: 'Find and replace', acceptedFormats: ['.xlsx', '.xls'], multipleFiles: false, settings: [] },
  { id: 'csv-delimiter-change', name: 'CSV Delimiter Change', category: 'excel', description: 'Change delimiter', acceptedFormats: ['.csv'], multipleFiles: false, settings: [] },
  { id: 'excel-pivot-table', name: 'Excel Pivot Table', category: 'excel', description: 'Create pivot table', acceptedFormats: ['.xlsx', '.xls'], multipleFiles: false, settings: [] },
  { id: 'excel-chart', name: 'Excel Chart', category: 'excel', description: 'Create charts', acceptedFormats: ['.xlsx', '.xls'], multipleFiles: false, settings: [] },
  { id: 'excel-conditional-formatting', name: 'Excel Conditional Format', category: 'excel', description: 'Apply formatting', acceptedFormats: ['.xlsx', '.xls'], multipleFiles: false, settings: [] },
  { id: 'excel-data-validation', name: 'Excel Data Validation', category: 'excel', description: 'Add validation', acceptedFormats: ['.xlsx', '.xls'], multipleFiles: false, settings: [] },
  { id: 'excel-vlookup', name: 'Excel VLOOKUP', category: 'excel', description: 'VLOOKUP operation', acceptedFormats: ['.xlsx', '.xls'], multipleFiles: true, settings: [] },
  { id: 'csv-json-convert', name: 'CSV to JSON', category: 'excel', description: 'Convert to JSON', acceptedFormats: ['.csv'], multipleFiles: false, settings: [] },
  { id: 'excel-protect', name: 'Excel Protect', category: 'excel', description: 'Protect file', acceptedFormats: ['.xlsx', '.xls'], multipleFiles: false, settings: [] },
  { id: 'excel-unprotect', name: 'Excel Unprotect', category: 'excel', description: 'Unprotect file', acceptedFormats: ['.xlsx', '.xls'], multipleFiles: false, settings: [] },
  { id: 'excel-formula-audit', name: 'Excel Formula Audit', category: 'excel', description: 'Audit formulas', acceptedFormats: ['.xlsx', '.xls'], multipleFiles: false, settings: [] },
  { id: 'excel-macro-remove', name: 'Excel Macro Remove', category: 'excel', description: 'Remove macros', acceptedFormats: ['.xlsm'], multipleFiles: false, settings: [] },
  { id: 'excel-template', name: 'Excel Template', category: 'excel', description: 'Use templates', acceptedFormats: ['.xlsx', '.xls'], multipleFiles: false, settings: [] },
  { id: 'excel-compare', name: 'Excel Compare', category: 'excel', description: 'Compare files', acceptedFormats: ['.xlsx', '.xls'], multipleFiles: true, settings: [] },

  // IMAGE TOOLS (30), VIDEO TOOLS (20), AUDIO TOOLS (15), ARCHIVE TOOLS (12), UTILITY TOOLS (25)
  // Continued in implementation...
];
